#!/usr/bin/env python3
"""Convert the Yale Bright Star Catalogue (BSC5) into Swiss `sefstars` format.

The stock sefstars.txt that ships with Swiss Ephemeris stops around magnitude 5
and carries a few hundred named stars. A star map needs the whole naked-eye sky,
so we convert all 9,110 BSC5 entries. Going through sefstars rather than
projecting the catalogue ourselves means the stars get exactly the same
precession, proper-motion and nutation path as the planets.

    uv run --project engine scripts/build_stars.py            # -> data/ephe/sefstars.txt
    uv run --project engine scripts/build_stars.py --check    # round-trip Sirius and Spica

BSC5 is public domain (Hoffleit & Warren 1991, ADC/CDS V/50). Its fixed-width
byte layout is documented in the catalogue's own ReadMe; the columns used here
are HR, Bayer/Flamsteed name, J2000 RA/Dec, proper motions, parallax, radial
velocity and V magnitude.
"""

from __future__ import annotations

import argparse
import gzip
import math
import sys
import urllib.request
from pathlib import Path

# The scripts live at the repository root; everything they write lives
# under engine/data, beside the package that reads it.
ROOT = Path(__file__).resolve().parent.parent / "engine"
CACHE = ROOT / "data" / "ephe" / "_cache"
# Swiss Ephemeris hardcodes the filename "sefstars.txt", so ours takes that
# name and the stock catalogue is kept beside it for the round-trip check.
OUT = ROOT / "data" / "ephe" / "sefstars.txt"
STOCK = ROOT / "data" / "ephe" / "sefstars_stock.txt"

BSC5_URL = "http://tdc-www.harvard.edu/catalogs/bsc5.dat.gz"

HEADER = """\
# sefstars.txt -- generated by scripts/build_stars.py, do not edit.
# Source: Yale Bright Star Catalogue, 5th Revised Edition (Hoffleit & Warren
# 1991, ADC/CDS V/50), public domain. {n} stars.
#
# Columns are the Swiss Ephemeris sefstars format:
#   traditional name, nomenclature name, equinox, RA h/m/s, Dec d/m/s,
#   pmRA (0.001"/yr * cos dec), pmDec (0.001"/yr), radial velocity (km/s),
#   parallax (0.001"), V magnitude
#
# The traditional name is HRnnnn so that every star is addressable by its
# Harvard Revised number; the nomenclature name carries the Bayer/Flamsteed
# designation where BSC5 has one.
"""


def slice_field(line: str, start: int, end: int) -> str:
    """BSC5 columns are 1-indexed and inclusive, as in the catalogue ReadMe."""
    return line[start - 1:end]


def parse_float(s: str, default: float = 0.0) -> float:
    s = s.strip()
    if not s:
        return default
    try:
        return float(s)
    except ValueError:
        return default


# Swiss abbreviates the Greek letter to two characters, except that omicron and
# omega need three to stay apart. Verified against the stock sefstars.txt.
GREEK = {
    "Alp": "al", "Bet": "be", "Gam": "ga", "Del": "de", "Eps": "ep",
    "Zet": "ze", "Eta": "et", "The": "th", "Iot": "io", "Kap": "ka",
    "Lam": "la", "Mu": "mu", "Nu": "nu", "Xi": "xi", "Omi": "omi",
    "Pi": "pi", "Rho": "rh", "Sig": "si", "Tau": "ta", "Ups": "up",
    "Phi": "ph", "Chi": "ch", "Psi": "ps", "Ome": "ome",
}


def nomenclature(raw: str) -> str:
    """BSC5 'Name' is a 10-character field: Flamsteed, Bayer, superscript, const.

    '  9Alp CMa' becomes 'alCMa' and ' 21    Tau' becomes '21Tau', which is the
    convention the stock sefstars.txt uses. A star we cannot parse gets an empty
    designation; its HR number still addresses it.
    """
    if not raw.strip():
        return ""
    flamsteed = raw[0:3].strip()
    greek = GREEK.get(raw[3:6].strip(), "")
    superscript = raw[6:7].strip()
    const = raw[7:10].strip()
    if not const:
        return raw.strip().replace(" ", "")
    if greek:
        return f"{greek}{superscript}{const}"
    return f"{flamsteed}{const}" if flamsteed else const


def convert(raw: str) -> list[str]:
    out = []
    for line in raw.splitlines():
        if len(line) < 107:
            continue
        hr = slice_field(line, 1, 4).strip()
        if not hr.isdigit():
            continue
        ra_h = slice_field(line, 76, 77).strip()
        if not ra_h:            # novae and other entries with no position
            continue
        ra_m = slice_field(line, 78, 79).strip()
        ra_s = slice_field(line, 80, 83).strip()
        de_sign = slice_field(line, 84, 84).strip() or "+"
        de_d = slice_field(line, 85, 86).strip()
        de_m = slice_field(line, 87, 88).strip()
        de_s = slice_field(line, 89, 90).strip()
        vmag = parse_float(slice_field(line, 103, 107), 99.0)
        pm_ra = parse_float(slice_field(line, 149, 154)) * 1000.0
        pm_de = parse_float(slice_field(line, 155, 160)) * 1000.0
        parallax = parse_float(slice_field(line, 162, 166)) * 1000.0
        radvel = parse_float(slice_field(line, 167, 170))

        # Swiss refuses to load the file if any nomenclature field is empty, so
        # a star with no Bayer or Flamsteed designation repeats its HR number.
        hr_name = f"HR{int(hr):04d}"
        designation = nomenclature(slice_field(line, 5, 14)) or hr_name

        out.append(
            f"{hr_name},{designation},2000,"
            f"{int(ra_h):02d},{int(ra_m):02d},{float(ra_s):07.4f},"
            f"{de_sign}{int(de_d):02d},{int(de_m):02d},{float(de_s):06.3f},"
            f"{pm_ra:.2f},{pm_de:.2f},{radvel:.1f},{parallax:.2f},{vmag:.2f}"
        )
    return out


def fetch_bsc5() -> str:
    CACHE.mkdir(parents=True, exist_ok=True)
    cached = CACHE / "bsc5.dat.gz"
    if not cached.exists():
        print(f"fetching {BSC5_URL} ...", flush=True)
        with urllib.request.urlopen(BSC5_URL, timeout=180) as r:
            cached.write_bytes(r.read())
    return gzip.decompress(cached.read_bytes()).decode("latin-1")


def stock_position(designation: str) -> tuple[float, float] | None:
    """Return (RA deg, Dec deg) for a nomenclature name in the stock file."""
    if not STOCK.exists():
        return None
    for line in STOCK.read_text(encoding="latin-1").splitlines():
        if line.startswith("#") or "," not in line:
            continue
        f = [c.strip() for c in line.split(",")]
        if len(f) < 9 or f[1] != designation:
            continue
        ra = (int(f[3]) + int(f[4]) / 60 + float(f[5]) / 3600) * 15
        sign = -1 if f[6].startswith("-") else 1
        dec = sign * (abs(int(f[6])) + int(f[7]) / 60 + float(f[8]) / 3600)
        return ra, dec
    return None


def check(lines: list[str]) -> int:
    """Round-trip the two stars the technical plan names against the stock file.

    BSC5 records J2000 RA to 0.1 s and Dec to 1", so the achievable agreement is
    set by that rounding, not by the conversion. Anything above a couple of
    arcseconds means the byte layout is being read wrongly.
    """
    failures = 0
    for designation in ("alCMa", "alVir"):
        ours = next((l for l in lines if l.split(",")[1] == designation), None)
        theirs = stock_position(designation)
        if ours is None or theirs is None:
            print(f"  {designation}: missing from one of the files", file=sys.stderr)
            failures += 1
            continue
        f = ours.split(",")
        ra = (int(f[3]) + int(f[4]) / 60 + float(f[5]) / 3600) * 15
        sign = -1 if f[6].startswith("-") else 1
        dec = sign * (abs(int(f[6])) + int(f[7]) / 60 + float(f[8]) / 3600)
        d_ra = (ra - theirs[0]) * 3600 * math.cos(math.radians(dec))
        d_dec = (dec - theirs[1]) * 3600
        sep = math.hypot(d_ra, d_dec)
        status = "ok" if sep < 2.0 else "FAIL"
        print(f"  {designation}: dRA {d_ra:+.3f}\" dDec {d_dec:+.3f}\" "
              f"sep {sep:.3f}\" [{status}]")
        failures += status == "FAIL"
    return failures


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="round-trip Sirius and Spica against the stock file")
    args = ap.parse_args()

    lines = convert(fetch_bsc5())
    OUT.write_text(HEADER.format(n=len(lines)) + "\n".join(lines) + "\n",
                   encoding="utf-8")
    print(f"{len(lines):,} stars -> {OUT.relative_to(ROOT)}")
    if args.check:
        return check(lines)
    return 0


if __name__ == "__main__":
    sys.exit(main())
